import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import ReactCountryFlag from 'react-country-flag'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter()
  const locale = router.locale || 'en'

  return (
    <div className={styles.container}>
      <Head>
        <title>react-pdf with use-intl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://react-pdf.org/">react-pdf</a> with{' '}
          <a href="https://www.npmjs.com/package/use-intl">use-intl</a>
        </h1>

        <div className={styles.lang}>
          <Link href="/" locale="en">
            <a>
              <ReactCountryFlag
                className={styles.flag}
                countryCode="US"
                style={{
                  fontSize: '2rem',
                }}
              />
            </a>
          </Link>
          <Link href="/" locale="de">
            <a>
              <ReactCountryFlag
                className={styles.flag}
                countryCode="DE"
                style={{
                  fontSize: '2rem',
                }}
              />
            </a>
          </Link>
        </div>

        <iframe
          className={styles.pdf}
          src={'http://localhost:3000/api/pdf?locale=' + locale}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
